#!/bin/sh

### BEGIN INIT INFO
# Provides:		harbor
# Required-Start:	$local_fs $remote_fs
# Required-Stop:	$local_fs $remote_fs
# X-Start-Before:
# X-Stop-After:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Description:		Runs the harbor services
# Short-Description:	Runs the harbor services
### END INIT INFO

. /lib/lsb/init-functions

source /etc/default/harbor

case "${1}" in
    start)
        log_daemon_msg "Starting harbor service" "harbor"
        start-stop-daemon --start --quiet --pidfile /var/run/harbor.pid --exec /root/platform/bin/start-harbor.sh -- --background /var/run/vmtoolsd.pid || exit 1
        log_end_msg 0
        ;;

    stop)
        log_daemon_msg "Stopping harbor service" "harbor"
        start-stop-daemon --stop --quiet --pidfile --pidfile /var/run/harbor.pid --exec /root/platform/bin/stop-harbor.sh
        RETURN="${?}"
        [ "${RETURN}" = 2 ] && exit 2
        # Many daemons don't delete their pidfiles when they exit.
        rm -f /var/run/harbor.pid
        log_end_msg 0
        ;;

    force-reload|restart)
        ${0} stop
        ${0} start
        ;;

    status)
        /root/platform/bin/status-harbor.sh && exit 0 || exit $?
        ;;

    *)
        log_success_msg "Usage: ${0} {start|stop|restart|force-reload|status}"
        exit 1
        ;;
esac
